<a href="https://colab.research.google.com/github/Revanth0710/AI-MLEngineer/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                      **NumPy**

Array Handling:
NumPy creates fast, powerful arrays (ndarray) for storing numbers efficiently.

Mathematical Operations:
It supports vectorized math — you can add, subtract, multiply arrays directly without loops.

Dimensions:

1D = Vector → [1, 2, 3]

2D = Matrix → [[1, 2], [3, 4]]

Supports 3D and more dimensions too!

Broadcasting:
Lets you automatically match array shapes for operations (small arrays stretch to fit big ones).

Foundation Library:
Most machine learning, AI, data science tools (like Pandas, TensorFlow) are built using NumPy.



In [ ]:
my_list =[1,2,3,4]

In [ ]:
my_list

[1, 2, 3, 4]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
# 2D array
my_math = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
my_math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

The np.arange() function in NumPy is used to generate a range of values in the form of a NumPy array. It creates an array of evenly spaced values based on the specified start, stop, and step parameters.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

The np.linspace() function in NumPy is used to generate an array of evenly spaced values over a specified range. Unlike np.arange(), which uses a step size to define the spacing between values, np.linspace() divides the interval into a specified number of equally spaced values.

In [ ]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

The np.eye() function in NumPy is used to create a 2D array (matrix) with ones on the diagonal and zeros elsewhere. This is known as an identity matrix.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.15830182, 0.21032361, 0.73081889, 0.63071708, 0.74175868])

The np.random.rand() function in NumPy is used to generate an array of random numbers drawn from a uniform distribution over the interval [0, 1). The shape of the array is specified by passing the dimensions as arguments.


In [ ]:
np.random.rand(5,5)

array([[0.18281116, 0.58622783, 0.24902826, 0.80863473, 0.14278174],
       [0.33926579, 0.58056131, 0.62077238, 0.34848492, 0.40333994],
       [0.19352946, 0.59801858, 0.85138661, 0.92710147, 0.43856703],
       [0.63287751, 0.59328481, 0.33416304, 0.15122323, 0.3169385 ],
       [0.98833139, 0.53510837, 0.75853445, 0.81765914, 0.54824145]])

np.random.randn() generates numbers from a normal (Gaussian) distribution with a mean of 0 and standard deviation of 1.


In [ ]:
np.random.randn(4,4)

array([[ 1.11254189, -1.91073004,  0.63283881,  0.46917289],
       [-0.00641353, -1.45269426,  0.29058625, -2.10493215],
       [-0.73142599, -0.40201221, -0.02875653,  1.12528226],
       [ 0.70099975, -0.96905655,  0.69832843,  0.07365726]])

The np.random.randint() function in NumPy is used to generate random integers within a specified range. You can specify the low (inclusive) and high (exclusive) bounds, as well as the size of the output array.


In [ ]:
np.random.randint(1,100, 10)

array([65, 80, 93, 84, 85, 61,  8, 49, 48, 74])

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(1,50,10)

In [ ]:
ranarr

array([39, 48,  3, 33, 18, 18, 39,  5, 23, 39])

In [ ]:
ranarr.max()

np.int64(48)

In [ ]:
ranarr.min()

np.int64(3)

In [ ]:
ranarr.argmax()

np.int64(1)

In [ ]:
ranarr.argmax()

np.int64(1)

The total number of elements in the original array must match the total number of elements in the reshaped array.

Reshaping does not change the data of the array; it simply changes its view.

In [ ]:
arr .reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

8

# NumPy Indexing and Selection


In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(arr[9])

9


In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_array = arr[:6]

In [ ]:
slice_array

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_array[:] = 99

In [ ]:
slice_array

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Creates a view of the original array — not a separate copy.

The slice shares the same memory as the original array.

Changing the slice will affect the original array (unless you explicitly copy it).

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
print(arr_2d[2,2])

45


In [ ]:
print(arr_2d[2][2])

45


In [ ]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [ ]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr> 5

In [ ]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Conditional Selection

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr<3]

array([1, 2])

In [ ]:
arr_2d = np.arange(50).reshape(5,10)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])

# NumPy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Scalar Operation

In [6]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [7]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [8]:
arr / arr

<ipython-input-8-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
1 / arr

<ipython-input-9-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [10]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
arr.max()

np.int64(10)

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])