<a href="https://colab.research.google.com/github/Revanth0710/AI-MLEngineer/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                      **NumPy**

Array Handling:
NumPy creates fast, powerful arrays (ndarray) for storing numbers efficiently.

Mathematical Operations:
It supports vectorized math — you can add, subtract, multiply arrays directly without loops.

Dimensions:

1D = Vector → [1, 2, 3]

2D = Matrix → [[1, 2], [3, 4]]

Supports 3D and more dimensions too!

Broadcasting:
Lets you automatically match array shapes for operations (small arrays stretch to fit big ones).

Foundation Library:
Most machine learning, AI, data science tools (like Pandas, TensorFlow) are built using NumPy.



In [ ]:
my_list =[1,2,3,4]

In [ ]:
my_list

[1, 2, 3, 4]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
# 2D array
my_math = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
my_math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

The np.arange() function in NumPy is used to generate a range of values in the form of a NumPy array. It creates an array of evenly spaced values based on the specified start, stop, and step parameters.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

The np.linspace() function in NumPy is used to generate an array of evenly spaced values over a specified range. Unlike np.arange(), which uses a step size to define the spacing between values, np.linspace() divides the interval into a specified number of equally spaced values.

In [ ]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

The np.eye() function in NumPy is used to create a 2D array (matrix) with ones on the diagonal and zeros elsewhere. This is known as an identity matrix.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.10367118, 0.7847633 , 0.50257086, 0.06450648, 0.16375884])

The np.random.rand() function in NumPy is used to generate an array of random numbers drawn from a uniform distribution over the interval [0, 1). The shape of the array is specified by passing the dimensions as arguments.


In [ ]:
np.random.rand(5,5)

array([[0.52141914, 0.06001598, 0.70283391, 0.1269463 , 0.20528058],
       [0.92390103, 0.51738079, 0.94584844, 0.29428314, 0.132813  ],
       [0.47573956, 0.80849667, 0.14622445, 0.51124912, 0.56784404],
       [0.98289371, 0.47884041, 0.56952536, 0.67530475, 0.05557629],
       [0.85416098, 0.0598583 , 0.24194645, 0.6287008 , 0.36343797]])

np.random.randn() generates numbers from a normal (Gaussian) distribution with a mean of 0 and standard deviation of 1.


In [ ]:
np.random.randn(4,4)

array([[-1.07610386,  0.04440501, -2.28796741, -0.08899019],
       [ 0.92248071,  1.92861461,  1.22609696, -0.17238412],
       [ 2.03530722, -0.51767145, -0.06946899, -0.76690214],
       [-0.2468622 ,  0.45380313,  1.37229148, -0.14651225]])

The np.random.randint() function in NumPy is used to generate random integers within a specified range. You can specify the low (inclusive) and high (exclusive) bounds, as well as the size of the output array.


In [ ]:
np.random.randint(1,100, 10)

array([33, 56, 28, 97, 32, 84, 71,  6, 11, 46])

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(1,50,10)

In [ ]:
ranarr

array([47, 22, 34, 48, 36, 32,  2, 26, 32, 29])

In [ ]:
ranarr.max()

np.int64(48)

In [ ]:
ranarr.min()

np.int64(2)

In [ ]:
ranarr.argmax()

np.int64(3)

In [ ]:
ranarr.argmax()

np.int64(3)

The total number of elements in the original array must match the total number of elements in the reshaped array.

Reshaping does not change the data of the array; it simply changes its view.

In [ ]:
arr .reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

3